### ISSUE TITLE
configurations for prism-shaped arena

### ISSUE THREAD

**Issue by chiyu1203** [jakemanger/fiddlercrabvr#4]
Dear Fiddlercrabvr team, 
I am trying to implement your software in our setup. I have managed to get the python environment right and see stimuli on one of the screens. However, the other screens do not look alike to what is described in your paper, so I reckon some settings for the monitors are off. Our setup is a prism-shaped arena made by three monitors and animals are tethered on an airball in the centre of the prism. Therefore, I wonder if there is example yaml files used in the Eristalis tenax hoverfly experiment and whether we can edit particular parameters to accommodate the design of our setup (for example, I placed the monitors horizontally to make the prism, unlike in the hoverfly experiment where the monitors are placed vertically).
Many thanks in advance!

**Comment by jakemanger** [comment]
Hi Chi-Yu,

Thanks for the interest. For the fiddlercrab experiments, the setup was four screens around the animal in the centre (differing to the hoverfly experiments), so you are right that the perspective settings for the monitors will be off. I'm sorry if this will be a little confusing, but the hoverfly experiment and fiddlercrab experiments used two different codebases. The hoverfly used CAVE (presented along with the paper) and the fiddlercrab experiments used another tool that I hope to publish along with my thesis this year. Both were included in the paper because of their shared use of machine vision for tracking the animal and closing the loop in the experiment.

You really have three options here:

1) See if the CAVE tool can be used to show the displays in the orientation you want. You will also need to swap out CAVE's DeepLabCut movement system with the fictrac one used here.

2) If you would prefer using the project in this repository (e.g. you want the same stimuli), I am also happy to add you as a contributor to the repository where you should be able to add features and rebuild the unity executable found here. Warning this won't be as user friendly as CAVE and will require some programming. Currently it's being used by us for our other generic stimuli in the lab for electrophysiology and behaviour and has a few more thing than the closed-loop VR experiment in the paper. I am currently working on the documentation for publication soon.

3) I can quickly add the feature to change to a 3 screen prism orientation and add a yaml config option for you. But, option 1 or 2 will likely be better if you want to modify the stimulus more (e.g. swap out the virtual crab or object).
